### ISSUE TITLE
Error activating IFilterProvider using binding from IFilterProvider to NinjectFilterAttributeFilterProvider

### ISSUE THREAD

**Issue by andyhot** [ninject/Ninject.Web.Mvc#13]
A cyclical dependency was detected between the constructors of two services.  Activation path:  1) Request for IFilterProvider

I keep getting this in a production server after a few hours of flawless execution. I don't see any other exceptions in the elmah logs and my current guess is that the server is reloading/restarting the app somehow and this leads to the exceptions. Of course, once those appear, the whole app is unusable. 

I'm using Ninject 2.2.0.0 and Ninject.Web.Mvc 2.2.0.3 and extend NinjectHttpApplication in my Global.asax.cs (Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.1; ASP.MVC 3)

Here's the full trace

<pre>
[ActivationException: Error activating IFilterProvider using binding from IFilterProvider to NinjectFilterAttributeFilterProvider
A cyclical dependency was detected between the constructors of two services.

Activation path:
  1) Request for IFilterProvider

Suggestions:
  1) Ensure that you have not declared a dependency for IFilterProvider on any implementations of the service.
  2) Consider combining the services into a single one to remove the cycle.
  3) Use property injection instead of constructor injection, and implement IInitializable
     if you need initialization logic to be run after property values have been injected.
]
   Ninject.Activation.Context.Resolve() in d:\BuildAgent-01\work\b68efe9aafe8875e\src\Ninject\Activation\Context.cs:148
   Ninject.KernelBase.<Resolve>b__7(IContext context) in d:\BuildAgent-01\work\b68efe9aafe8875e\src\Ninject\KernelBase.cs:375
   System.Linq.<>c__DisplayClass12`3.<CombineSelectors>b__11(TSource x) +32
   System.Linq.WhereSelectEnumerableIterator`2.MoveNext() +151
   System.Linq.<CastIterator>d__b1`1.MoveNext() +92
   System.Linq.<ConcatIterator>d__71`1.MoveNext() +117
   System.Linq.<SelectManyIterator>d__14`2.MoveNext() +399
   System.Linq.Buffer`1..ctor(IEnumerable`1 source) +217
   System.Linq.<GetEnumerator>d__0.MoveNext() +96
   System.Linq.Buffer`1..ctor(IEnumerable`1 source) +217
   System.Linq.<ReverseIterator>d__a0`1.MoveNext() +93
   System.Web.Mvc.<RemoveDuplicates>d__b.MoveNext() +131
   System.Linq.Buffer`1..ctor(IEnumerable`1 source) +217
   System.Linq.<ReverseIterator>d__a0`1.MoveNext() +93
   System.Linq.WhereSelectEnumerableIterator`2.MoveNext() +87
   System.Linq.<OfTypeIterator>d__aa`1.MoveNext() +88
   System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection) +395
   System.Web.Mvc.FilterInfo..ctor(IEnumerable`1 filters) +248
   System.Web.Mvc.ControllerActionInvoker.GetFilters(ControllerContext controllerContext, ActionDescriptor actionDescriptor) +47
   System.Web.Mvc.ControllerActionInvoker.InvokeAction(ControllerContext controllerContext, String actionName) +128
   System.Web.Mvc.Controller.ExecuteCore() +115
   System.Web.Mvc.ControllerBase.Execute(RequestContext requestContext) +94
   System.Web.Mvc.ControllerBase.System.Web.Mvc.IController.Execute(RequestContext requestContext) +10
   System.Web.Mvc.<>c__DisplayClassb.<BeginProcessRequest>b__5() +37
   System.Web.Mvc.Async.<>c__DisplayClass1.<MakeVoidDelegate>b__0() +21
   System.Web.Mvc.Async.<>c__DisplayClass8`1.<BeginSynchronous>b__7(IAsyncResult _) +12
   System.Web.Mvc.Async.WrappedAsyncResult`1.End() +55
   System.Web.Mvc.<>c__DisplayClasse.<EndProcessRequest>b__d() +31
   System.Web.Mvc.SecurityUtil.<GetCallInAppTrustThunk>b__0(Action f) +7
   System.Web.Mvc.SecurityUtil.ProcessInApplicationTrust(Action action) +23
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +59
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +8841105
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +184
</pre>

**Comment by Marusyk** [comment]
This exact error message still happens for me in the last version of Ninject
