### ISSUE TITLE
NinjectWebCommon.cs do not appear

### ISSUE THREAD

**Issue by nivinjoe** [ninject/Ninject.Web.Mvc#45]
Ninject.MVC5 installing fine , but not creating the required NinjectWebCommon.cs files .. VS 2015 enterprise version with 4.7 framework

**Comment by dskc** [comment]
I'm also surprised to realise the same.. guess that something has to be written at StartUp.CS file. Is anyone reading this query!!! This has been unanswered since 21st Nov

**Comment by scott-xu** [comment]
Source and configuration file transformations are not applied when a package is installed in a project using Package References in project files.
see https://docs.microsoft.com/en-us/nuget/create-packages/source-and-config-file-transformations
You need to do it manually.
